export const SAMPLE_CAD: Record<string, any> = {
  grupo: ["BERMUDA","CALCA","CAMISA","CAMISETA","CASACO","JAQUETA","OVERSHIRT","POLO"],
  subgrupo: ["JOGGER","JOGGER CARGO","CÓS FIXO CHINO","CÓS FIXO FIVE POCKETS","SHORTS JOGGER","BERMUDA JOGGER","BOARDSHORTS","SWIMSHORTS","S/BOLSO MANGA LONGA","S/BOLSO MANGA CURTA","C/BOLSO MANGA LONGA","C/BOLSO MANGA CURTA","CUBANA MANGA CURTA","CUBANA MANGA LONGA","GOLA CARECA MC BASICA","GOLA CARECA MC DIFERENCIADA","GOLA CARECA ML DIFERENCIADA","HENLEY DIFERENCIADA MC","MOLETOM CANGURU","OVERSHIRT","POLO MANGA CURTA","POLO MANGA LONGA"],
  categoria: ["FLANELA","VELUDO","LINHO","MALHA","NYLON","TRICOLINE","FLEECE","MOLETOM","PLANO","SARJA","DENIM","LYOCELL","VISCOSE"],
  subcategoria: ["LISO","XADREZ","ESTAMPADO","SILK FRENTE","SILK PEITO","SILK COSTAS","LISTRADO","BLACK DENIM"],
  linha: ["CASUAL","EARTH","GRAPHIC","OUTDOOR","CONCEPT","DOWNWIND","BLACK"],
  grade: ["XPP-GG","PP-GG","38-46","ÚNICO"],
  operacao: ["INTERNO","TERCEIRIZADO","SEMI-TERCEIRIZADO"],
  tipo: ["COR FIRME","REATIVO","ESTONADO","MARMORIZADO","PURGA"],
  fornecedor: ["CH GARMENT","CONVÉS","COR A COR","DOPIO SENSO","DSK","EC","GNG","GRADUAL","HC BRASIL","JHR","JUMA","K2","LAC TÊXTIL","LEO HOLANDA","LETOCHE","MUTUAL","PL","RIZZATTI","SEEDER","VAPE","VILLA TEXTIL"],
  drop: ["0","1","2","3"],
  colecao: ["VERÃO 27","CLÁSSICOS","INVERNO 26","GAIA","COPA 26","BAMBA","XP INC."],
  cor: ["C01 - BRANCO","C02 - PRETO","C03 - OFF WHITE","C04 - NATURAL","C05 - BEGE","C06 - AZUL CLARO","C07 - AZUL ESCURO","C08 - CINZA CLARO","C09 - CINZA ESCURO","C10 - VERDE","C11 - MARROM","C13 - CORAL","C14 - VD CLARO","C17 - AMARELO","C20 - AREIA","C25 - KHAKI"],
  status: ["DESENVOLVIMENTO","MOSTRUÁRIO LIBERADO","PRODUÇÃO LIBERADA","CANCELADO"],
  piloto_most: ["PILOTO","MOSTRUÁRIO DIRETO"],
  tecido: [
    { nome: "MOLETOM COPAT", forn: "COPAT", comp: "80% CO, 20% PES", preco: "" },
    { nome: "ETBQP - QUÊNIA", forn: "HUDTELFA", comp: "98% CO, 2% PUE", preco: "14.90" },
    { nome: "LINHO PIENZA ECO", forn: "MN", comp: "100% LI", preco: "" },
    { nome: "GAZE FLAMÊ K2", forn: "K2", comp: "100% CO", preco: "" },
    { nome: "MALHA 30/01", forn: "STICLE", comp: "100% CO", preco: "" },
    { nome: "TABHAE1054 - SPINNING PLUS", forn: "VICUNHA", comp: "98% CO, 2% PUE", preco: "" },
    { nome: "500/4717.0.000 NEW HYBRID MEGAFLEX", forn: "CANATIBA", comp: "", preco: "" },
  ],
};

export const SAMPLE_ROWS = [
  {
    id: 1, base: "0", ref: "21.01.00.43", desc: "CALÇA MOLETOM JOGGER BASIC",
    tecido: "MOLETOM COPAT", forn_tecido: "COPAT", status: "MOSTRUÁRIO LIBERADO",
    piloto_most: "MOSTRUÁRIO DIRETO", colecao: "VERÃO 27", link_ficha: "",
    grupo: "CALCA", subgrupo: "JOGGER", operacao: "SEMI-TERCEIRIZADO",
    fornecedor: "COR A COR", grade: "PP-GG", cod_cor: "C07", nome_cor: "AZUL ESCURO",
    categoria: "MOLETOM", subcategoria: "LISO", lavagem: "COR FIRME",
    base2: "CALÇA JOGGER", tipo: "COR FIRME", linha: "CASUAL", drop: "2",
    estilista: "THABATA",
    ficha: {
      tabelaMedidas: "CALÇA JOGGER",
      tecidos: [{ artigo: "MOLETOM COPAT", forn: "COPAT", preco: 0, cores: ["PRETO","CINZA CHUMBO","AZUL MARINHO"] }],
      aviamentos: [
        { item: "Adesivo cód. barras", cod: "AD0001", qtd: 1, valor: 0.10, local: "Colado verso do tag" },
        { item: "Tag Casual", cod: "TA0003", qtd: 1, valor: 0.50, local: "Aplicado c/ lacre preto na etiqueta interna" },
        { item: "Etiqueta marca média", cod: "ET0045", qtd: 1, valor: 0.39, local: "Costurado apenas nas laterais sobre a parte inferior do cobre gola" },
        { item: "Etiqueta marca pinguim", cod: "ET0082", qtd: 1, valor: 0.70, local: "Aplicado no bolso costas, a 1cm da lateral" },
        { item: "Ilhós personalizado", cod: "IL17CA01", qtd: 2, valor: 0.20, local: "Centralizado no cós com 8cm de distância entre si" },
      ],
      pilotagem: [{ num: "Piloto 1", lacre: "", envio: "", receb: "", prova: "", status: "Aguardando" }],
    },
  },
  {
    id: 2, base: "0", ref: "21.01.00.43", desc: "CALÇA MOLETOM JOGGER BASIC",
    tecido: "MOLETOM COPAT", forn_tecido: "COPAT", status: "MOSTRUÁRIO LIBERADO",
    piloto_most: "MOSTRUÁRIO DIRETO", colecao: "VERÃO 27", link_ficha: "",
    grupo: "CALCA", subgrupo: "JOGGER", operacao: "SEMI-TERCEIRIZADO",
    fornecedor: "COR A COR", grade: "PP-GG", cod_cor: "C02", nome_cor: "PRETO",
    categoria: "MOLETOM", subcategoria: "LISO", lavagem: "COR FIRME",
    base2: "CALÇA JOGGER", tipo: "COR FIRME", linha: "CASUAL", drop: "2",
    estilista: "THABATA", ficha: null,
  },
  {
    id: 3, base: "1", ref: "21.01.00.43", desc: "CALÇA MOLETOM JOGGER BASIC",
    tecido: "MOLETOM COPAT", forn_tecido: "COPAT", status: "MOSTRUÁRIO LIBERADO",
    piloto_most: "MOSTRUÁRIO DIRETO", colecao: "VERÃO 27", link_ficha: "",
    grupo: "CALCA", subgrupo: "JOGGER", operacao: "SEMI-TERCEIRIZADO",
    fornecedor: "COR A COR", grade: "PP-GG", cod_cor: "C09", nome_cor: "CINZA ESCURO",
    categoria: "MOLETOM", subcategoria: "LISO", lavagem: "COR FIRME",
    base2: "CALÇA JOGGER", tipo: "COR FIRME", linha: "CASUAL", drop: "2",
    estilista: "THABATA", ficha: null,
  },
  {
    id: 4, base: "0", ref: "21.02.00.06", desc: "SHORTS JOGGER ANGRA",
    tecido: "ETBQP - QUÊNIA", forn_tecido: "HUDTELFA", status: "MOSTRUÁRIO LIBERADO",
    piloto_most: "PILOTO", colecao: "VERÃO 27", link_ficha: "",
    grupo: "BERMUDA", subgrupo: "SHORTS JOGGER", operacao: "TERCEIRIZADO",
    fornecedor: "CONVÉS", grade: "PP-GG", cod_cor: "C10", nome_cor: "VERDE",
    categoria: "SARJA", subcategoria: "LISO", lavagem: "ESTONADO",
    base2: "SHORTS JOGGER", tipo: "ESTONADO", linha: "CASUAL", drop: "2",
    estilista: "LIVIA", ficha: null,
  },
  {
    id: 5, base: "0", ref: "11.03.01.01", desc: "CAMISA LINHO BELIZE MANGA LONGA",
    tecido: "LINHO PIENZA ECO", forn_tecido: "MN", status: "MOSTRUÁRIO LIBERADO",
    piloto_most: "MOSTRUÁRIO DIRETO", colecao: "CLÁSSICOS", link_ficha: "",
    grupo: "CAMISA", subgrupo: "S/BOLSO MANGA LONGA", operacao: "TERCEIRIZADO",
    fornecedor: "DSK", grade: "PP-GG", cod_cor: "C06", nome_cor: "AZUL CLARO",
    categoria: "LINHO", subcategoria: "LISO", lavagem: "COR FIRME",
    base2: "CAMISA MANGA LONGA SLIM", tipo: "COR FIRME", linha: "CASUAL", drop: "2",
    estilista: "LIVIA", ficha: null,
  },
  {
    id: 6, base: "0", ref: "21.02.00.07", desc: "BERMUDA JOGGER ENSEADA",
    tecido: "500/4717.0.000 NEW HYBRID MEGAFLEX", forn_tecido: "CANATIBA", status: "MOSTRUÁRIO LIBERADO",
    piloto_most: "PILOTO", colecao: "VERÃO 27", link_ficha: "",
    grupo: "BERMUDA", subgrupo: "BERMUDA JOGGER", operacao: "TERCEIRIZADO",
    fornecedor: "VAPE", grade: "PP-GG", cod_cor: "C25", nome_cor: "KHAKI",
    categoria: "SARJA", subcategoria: "LISO", lavagem: "ESTONADO",
    base2: "BERMUDA JOGGER", tipo: "ESTONADO", linha: "CASUAL", drop: "1",
    estilista: "LIVIA", ficha: null,
  },
];
