// Dados de exemplo para desenvolvimento local.
// Quando o Supabase estiver conectado, esses dados vêm do banco.

export const SAMPLE_CAD: Record<string, any> = {
  grupo: ["BERMUDA", "CALCA", "CAMISA", "CAMISETA", "CASACO", "JAQUETA", "OVERSHIRT", "POLO"],
  subgrupo: ["JOGGER", "JOGGER CARGO", "CÓS FIXO CHINO", "CÓS FIXO FIVE POCKETS", "SHORTS JOGGER", "BERMUDA JOGGER", "BOARDSHORTS", "SWIMSHORTS", "S/BOLSO MANGA LONGA", "S/BOLSO MANGA CURTA", "C/BOLSO MANGA LONGA", "CUBANA MANGA CURTA", "GOLA CARECA MC BASICA", "GOLA CARECA MC DIFERENCIADA", "GOLA CARECA ML DIFERENCIADA", "MOLETOM CANGURU", "OVERSHIRT", "POLO MANGA CURTA", "POLO MANGA LONGA"],
  categoria: ["LINHO", "MALHA", "NYLON", "FLEECE", "MOLETOM", "PLANO", "SARJA", "DENIM", "LYOCELL"],
  subcategoria: ["LISO", "XADREZ", "ESTAMPADO", "SILK FRENTE", "SILK COSTAS", "LISTRADO"],
  linha: ["CASUAL", "EARTH", "GRAPHIC", "OUTDOOR", "BLACK"],
  grade: ["XPP-GG", "PP-GG", "38-46", "ÚNICO"],
  operacao: ["INTERNO", "TERCEIRIZADO", "SEMI-TERCEIRIZADO"],
  tipo: ["COR FIRME", "REATIVO", "ESTONADO", "MARMORIZADO"],
  fornecedor: ["CONVÉS", "COR A COR", "DSK", "EC", "GNG", "GRADUAL", "JHR", "K2", "LAC TÊXTIL", "LETOCHE", "MUTUAL", "PL", "RIZZATTI", "SEEDER", "VAPE"],
  drop: ["0", "1", "2", "3"],
  colecao: ["VERÃO 27", "CLÁSSICOS", "INVERNO 26", "GAIA", "COPA 26"],
  cor: ["C01 - BRANCO", "C02 - PRETO", "C03 - OFF WHITE", "C04 - NATURAL", "C06 - AZUL CLARO", "C07 - AZUL ESCURO", "C08 - CINZA CLARO", "C09 - CINZA ESCURO", "C10 - VERDE", "C11 - MARROM", "C13 - CORAL", "C20 - AREIA", "C25 - KHAKI"],
  status: ["DESENVOLVIMENTO", "MOSTRUÁRIO LIBERADO", "PRODUÇÃO LIBERADA", "CANCELADO"],
  tecido: [
    { nome: "MOLETOM COPAT", forn: "COPAT", comp: "80% CO, 20% PES", preco: "" },
    { nome: "ETBQP - QUÊNIA", forn: "HUDTELFA", comp: "98% CO, 2% PUE", preco: "14.90" },
    { nome: "LINHO PIENZA ECO", forn: "MN", comp: "100% LI", preco: "" },
    { nome: "GAZE FLAMÊ K2", forn: "K2", comp: "100% CO", preco: "" },
    { nome: "MALHA 30/01", forn: "STICLE", comp: "100% CO", preco: "" },
  ],
};

export const SAMPLE_ROWS = [
  {
    id: 1,
    ref: "21.01.00.43",
    desc: "Calça Moletom Jogger Basic",
    tecido: "MOLETOM COPAT",
    forn_tecido: "COPAT",
    status: "MOSTRUÁRIO LIBERADO",
    colecao: "VERÃO 27",
    grupo: "CALCA",
    subgrupo: "JOGGER",
    operacao: "SEMI-TERCEIRIZADO",
    fornecedor: "COR A COR",
    grade: "PP-GG",
    cor: "C07 - AZUL ESCURO",
    categoria: "MOLETOM",
    subcategoria: "LISO",
    lavagem: "COR FIRME",
    tipo: "COR FIRME",
    linha: "CASUAL",
    drop: "2",
    estilista: "Thabata",
    custo_forn: 0,
    custo_total: 2.25,
    mkp: 0,
    ficha: {
      tabelaMedidas: "CALÇA JOGGER",
      tecidos: [
        { artigo: "MOLETOM COPAT", forn: "COPAT", preco: 0, cores: ["PRETO", "CINZA CHUMBO", "AZUL MARINHO"] },
      ],
      aviamentos: [
        { item: "Adesivo cód. barras", cod: "AD0001", qtd: 1, valor: 0.10, local: "Colado verso do tag" },
        { item: "Tag Casual", cod: "TA0003", qtd: 1, valor: 0.50, local: "Aplicado c/ lacre preto" },
        { item: "Etiqueta marca média", cod: "ET0045", qtd: 1, valor: 0.39, local: "Costurado nas laterais" },
        { item: "Etiqueta pinguim", cod: "ET0082", qtd: 1, valor: 0.70, local: "Bolso costas" },
        { item: "Ilhós", cod: "IL17CA01", qtd: 2, valor: 0.20, local: "Centralizado no cós" },
      ],
      pilotagem: [
        { num: "Piloto 1", lacre: "", envio: "", receb: "", prova: "", status: "Aguardando" },
      ],
    },
  },
  {
    id: 2,
    ref: "21.01.00.43",
    desc: "Calça Moletom Jogger Basic",
    tecido: "MOLETOM COPAT",
    forn_tecido: "COPAT",
    status: "MOSTRUÁRIO LIBERADO",
    colecao: "VERÃO 27",
    grupo: "CALCA",
    subgrupo: "JOGGER",
    operacao: "SEMI-TERCEIRIZADO",
    fornecedor: "COR A COR",
    grade: "PP-GG",
    cor: "C02 - PRETO",
    categoria: "MOLETOM",
    subcategoria: "LISO",
    lavagem: "COR FIRME",
    tipo: "COR FIRME",
    linha: "CASUAL",
    drop: "2",
    estilista: "Thabata",
    custo_forn: 0,
    custo_total: 2.25,
    mkp: 0,
    ficha: null,
  },
  {
    id: 3,
    ref: "21.02.00.06",
    desc: "Shorts Jogger Angra",
    tecido: "ETBQP - QUÊNIA",
    forn_tecido: "HUDTELFA",
    status: "MOSTRUÁRIO LIBERADO",
    colecao: "VERÃO 27",
    grupo: "BERMUDA",
    subgrupo: "SHORTS JOGGER",
    operacao: "TERCEIRIZADO",
    fornecedor: "CONVÉS",
    grade: "PP-GG",
    cor: "C10 - VERDE",
    categoria: "SARJA",
    subcategoria: "LISO",
    lavagem: "ESTONADO",
    tipo: "ESTONADO",
    linha: "CASUAL",
    drop: "2",
    estilista: "Livia",
    custo_forn: 81,
    custo_total: 81,
    mkp: 445.5,
    ficha: null,
  },
  {
    id: 4,
    ref: "11.03.01.01",
    desc: "Camisa Linho Belize ML",
    tecido: "LINHO PIENZA ECO",
    forn_tecido: "MN",
    status: "MOSTRUÁRIO LIBERADO",
    colecao: "CLÁSSICOS",
    grupo: "CAMISA",
    subgrupo: "S/BOLSO MANGA LONGA",
    operacao: "TERCEIRIZADO",
    fornecedor: "DSK",
    grade: "PP-GG",
    cor: "C06 - AZUL CLARO",
    categoria: "LINHO",
    subcategoria: "LISO",
    lavagem: "COR FIRME",
    tipo: "COR FIRME",
    linha: "CASUAL",
    drop: "2",
    estilista: "Livia",
    custo_forn: 99.99,
    custo_total: 99.99,
    mkp: 549.95,
    ficha: null,
  },
];
